

Ext.define('Atlas.macprice.model.MacConfiguration', {
    extend: 'Atlas.common.model.Base',
    idProperty: 'systemID',
    fields: [
        {name: 'KeyValue', type: 'string', mapping: 'ItemCode'},
        {
            name: 'ChangeBy', type: 'string',
            calculate: function (data) {
                return Atlas.user.un;
            }
        },
        {name: 'included', type: 'boolean'},
        {name: 'GPIorNDC', type: 'string'},
        {name: 'ItemCode', type: 'string'},
        {name: 'ItemName', type: 'string'},
        {name: 'GPICode', type: 'string'},
        {name: 'GPIName', type: 'string'},
        {name: 'GCNSeqNo', type: 'number'},
        {name: 'GNN60', type: 'string'},
        {name: 'drugTypeFDB', type: 'string'},
        {name: 'drugTypeMDB', type: 'string'},
        {name: 'MACEffDate', type: 'date', dateFormat: 'Y-m-d'},
        {name: 'userMac', type: 'number'},
        {name: 'sysMac',  type: 'number'},
        {name: 'suggMAc', type: 'number'},
        {name: 'currAWP', type: 'number'},
        {name: 'currWAC', type: 'number'},
        {name: 'currFUL', type: 'number'},
        {name: 'MIMAC', type: 'number'},
        {name: 'PctOfAWP85', type: 'number'},
        {name: 'totRxCurrMonth', type: 'number'},
        {name: 'totQtyCurrMont', type: 'number'},
        {name: 'totIngCurrMont', type: 'number'},
        {name: 'avgIngCurrMont', type: 'number'},
        {name: 'mktRxCurrMonth', type: 'number'},
        {name: 'mktQtyCurrMont', type: 'number'},
        {name: 'mktIngCurrMont', type: 'number'},
        {name: 'totRxLastMonth', type: 'number'},
        {name: 'totQtyLastMont', type: 'number'},
        {name: 'totIngLastMont', type: 'number'},
        {name: 'avgIngLastMont', type: 'number'},
        {name: 'mktRxLastMonth', type: 'number'},
        {name: 'mktQtyLastMont', type: 'number'},
        {name: 'mktIngLastMont', type: 'number'},
        {name: 'totRxLast3Mths', type: 'number'},
        {name: 'totQtyLast3Mth', type: 'number'},
        {name: 'totIngLast3Mth', type: 'number'},
        {name: 'avgIngLast3Mth', type: 'number'},
        {name: 'mktRxLast3Mths', type: 'number'},
        {name: 'mktQtyLast3Mth', type: 'number'},
        {name: 'mktIngLast3Mth', type: 'number'},
        {name: 'totRxLastQtr',   type: 'number'},
        {name: 'totQtyLastQtr',  type: 'number'},
        {name: 'totIngLastQtr',  type: 'number'},
        {name: 'avgIngLastQtr',  type: 'number'},
        {name: 'mktRxLastQtr',   type: 'number'},
        {name: 'mktQtyLastQtr',  type: 'number'},
        {name: 'mktIngLastQtr',  type: 'number'},
        {name: 'totRxLast6Mths', type: 'number'},
        {name: 'totQtyLast6Mth', type: 'number'},
        {name: 'totIngLast6Mth', type: 'number'},
        {name: 'avgIngLast6Mth', type: 'number'},
        {name: 'mktRxLast6Mths', type: 'number'},
        {name: 'mktQtyLast6Mth', type: 'number'},
        {name: 'mktIngLast6Mth', type: 'number'},
        {name: 'totRxLastYear ', type: 'number'},
        {name: 'totQtyLastYear', type: 'number'},
        {name: 'totIngLastYear', type: 'number'},
        {name: 'avgIngLastyear', type: 'number'},
        {name: 'mktRxLastYear ', type: 'number'},
        {name: 'mktQtyLastYear', type: 'number'},
        {name: 'mktIngLastYear', type: 'number'},
        {name: 'totRxYTD',       type: 'number'},
        {name: 'totQtyYTD',      type: 'number'},
        {name: 'totIngYTD',      type: 'number'},
        {name: 'avgIngYTD',      type: 'number'},
        {name: 'mktRxYTD',       type: 'number'},
        {name: 'mktQtyYTD',      type: 'number'},
        {name: 'mktIngYTD',      type: 'number'},
        {name: 'lastModified', dateFormat: 'Y-m-d'},
        {name: 'covFormularies', type: 'string'},
        {name: 'systemID', type: 'number'},
        {name: 'rowNum', type: 'number'},
        {name: 'rowID', type: 'string'}

    ],
    proxy: {
        extraParams: {
            pagination: true
        },
        url: 'formulary/{0}/macdata',
        timeout: 120000
    }
});