/*
 Last Developer: Ankit Kumar
 Previous Developers: [Ankit Kumar]
 Origin: Merlin - MAC and Custom price
 Date: 7/26/2016
 Description: Mac Setup Model
 */

Ext.define('Atlas.macprice.model.MacPharmacyPricingInqExport', {
    extend: 'Atlas.common.model.Base',
    fields: [
        { name: 'InquiryDate', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'inquiryStatus', type: 'string'},
        { name: 'NCPDPID', type: 'string'},
        { name: 'PharState', type: ''},
        { name: 'NAME', type: 'string'},
        { name: 'NDC', type: 'string'},
        { name: 'LN', type: 'string'},
        { name: 'GPICode', type: 'string'},
        { name: 'GPIName', type: 'string'},
        { name: 'GCNSeqNo', type: 'number'},
        { name: 'GNN60', type: 'string'},
        { name: 'drugTypeFDB', type: 'string'},
        { name: 'drugTypeMDB', type: 'string'},
        { name: 'currAWP', type: 'number'},
        { name: 'currWAC', type: 'number'},
        { name: 'MIMAC', type: 'number'},

        { name: 'contactEmail', type: 'string'},
        { name: 'contactFax', type: 'string'},
        { name: 'contactName', type: 'string'},
        { name: 'contactPhone', type: 'string'},
        { name: 'comments', type: 'string'},

        { name: 'claimID', type: 'number'},
        { name: 'claimDate', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'RxNum', type: 'string'},
        { name: 'paidAmt', type: 'number'},
        { name: 'pharmacyCost', type: 'number'},
        { name: 'proposedBy', type: 'string'},
        { name: 'proposedDate', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'reviewDate', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'reviewedBy', type: 'string'},
        { name: 'suggestedMAC', type: 'number'},
        { name: 'totRxCurrMonth', type: 'number'},
        { name: 'totQtyCurrMonth', type: 'number'},
        { name: 'totIngCurrMonth', type: 'number'},
        { name: 'avgIngCurrMonth', type: 'number'},
        { name: 'mktRxCurrMonth', type: 'number'},
        { name: 'mktQtyCurrMonth', type: 'number'},
        { name: 'mktIngCurrMonth', type: 'number'},
        { name: 'totRxLastMonth', type: 'number'},
        { name: 'totQtyLastMonth', type: 'number'},
        { name: 'totIngLastMonth', type: 'number'},
        { name: 'avgIngLastMonth', type: 'number'},
        { name: 'mktRxLastMonth', type: 'number'},
        { name: 'mktQtyLastMonth', type: 'number'},
        { name: 'mktIngLastMonth', type: 'number'},
        { name: 'totRxLast3Mths', type: 'number'},
        { name: 'totQtyLast3Mths', type: 'number'},
        { name: 'totIngLast3Mths', type: 'number'},
        { name: 'avgIngLast3Mths', type: 'number'},
        { name: 'mktRxLast3Mths', type: 'number'},
        { name: 'mktQtyLast3Mths', type: 'number'},
        { name: 'mktIngLast3Mths', type: 'number'},
        { name: 'totRxLastQtr', type: 'number'},
        { name: 'totQtyLastQtr', type: 'number'},
        { name: 'totIngLastQtr', type: 'number'},
        { name: 'avgIngLastQtr', type: 'number'},
        { name: 'mktRxLastQtr', type: 'number'},
        { name: 'mktQtyLastQtr', type: 'number'},
        { name: 'mktIngLastQtr', type: 'number'},
        { name: 'totRxLast6Mths', type: 'number'},
        { name: 'totQtyLast6Mths', type: 'number'},
        { name: 'totIngLast6Mths', type: 'number'},
        { name: 'avgIngLast6Mths', type: 'number'},
        { name: 'mktRxLast6Mths', type: 'number'},
        { name: 'mktQtyLast6Mths', type: 'number'},
        { name: 'mktIngLast6Mths', type: 'number'},
        { name: 'totRxLastYear', type: 'number'},
        { name: 'totQtyLastYear', type: 'number'},
        { name: 'totIngLastYear', type: 'number'},
        { name: 'avgIngLastyear', type: 'number'},
        { name: 'mktRxLastYear', type: 'number'},
        { name: 'mktQtyLastYear', type: 'number'},
        { name: 'mktIngLastYear', type: 'number'},
        { name: 'totRxYTD', type: 'number'},
        { name: 'totQtyYTD', type: 'number'},
        { name: 'totIngYTD', type: 'number'},
        { name: 'avgIngYTD', type: 'number'},
        { name: 'mktRxYTD', type: 'number'},
        { name: 'mktQtyYTD', type: 'number'},
        { name: 'mktIngYTD', type: 'number'},

        { name: 'StateMacMIDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacMI', type: 'number'},
        { name: 'StateMacOHDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacOH', type: 'number'},
        { name: 'StateMacNHDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacNH', type: 'number'},
        { name: 'StateMacILDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacIL', type: 'number'},
        { name: 'StateMacIWDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacIW', type: 'number'},
        { name: 'StateMacINDT', type: 'date', dateFormat: 'Y-m-d'},
        { name: 'StateMacIN', type: 'number'},
        { name: 'confirmationNum', type: 'number'},
        { name: 'PCN', type: 'string'},
        { name: 'mcsProgramCode', type: 'string'}
    ],
    proxy: {
        extraParams: {
            pagination: true
        },

        url: 'formulary/{0}/pharmacypricinginquiries',
        timeout: 120000
    }
});