//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnftPlanConfgPrpty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BnftPlanConfgPrpty()
        {
            this.BnftPlanConfgPrptyCrtriaSet = new HashSet<BnftPlanConfgPrptyCrtriaSet>();
        }
    
        public long BnftPlanConfgPrptySK { get; set; }
        public long BnftPlanSK { get; set; }
        public Nullable<long> BnftPlanBnftSK { get; set; }
        public Nullable<long> NtwrkTierSK { get; set; }
        public long ConfgPrptyTypeSK { get; set; }
        public string ConfgPrptyVal { get; set; }
        public int ConfgPrptyDsplyPrity { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        public virtual BnftPlanBnft BnftPlanBnft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanConfgPrptyCrtriaSet> BnftPlanConfgPrptyCrtriaSet { get; set; }
        public virtual ConfgPrptyType ConfgPrptyType { get; set; }
        public virtual NtwrkTier NtwrkTier { get; set; }
    }
}
