//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnftPlanPharmType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BnftPlanPharmType()
        {
            this.BnftPlanPharmTypeDaySupl = new HashSet<BnftPlanPharmTypeDaySupl>();
        }
    
        public long BnftPlanPharmTypeSK { get; set; }
        public long BnftPlanSK { get; set; }
        public long PharmTypeSK { get; set; }
        public Nullable<decimal> EarlyRefillPct { get; set; }
        public Nullable<int> MaxDaySuplMntncMedications { get; set; }
        public Nullable<int> MaxDaySuplNonMntncMedications { get; set; }
        public Nullable<decimal> MaxCostPerRx { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanPharmTypeDaySupl> BnftPlanPharmTypeDaySupl { get; set; }
        public virtual PharmType PharmType { get; set; }
    }
}
