//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BnftPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BnftPlan()
        {
            this.DeducblEpsd = new HashSet<DeducblEpsd>();
            this.DeducblEpsd1 = new HashSet<DeducblEpsd>();
            this.BnftPlanBnft = new HashSet<BnftPlanBnft>();
            this.PBPBnftPlan = new HashSet<PBPBnftPlan>();
            this.DataCompareDtl = new HashSet<DataCompareDtl>();
            this.BnftPlanConfgPrpty = new HashSet<BnftPlanConfgPrpty>();
            this.BnftPlanWvrRider = new HashSet<BnftPlanWvrRider>();
            this.NtwrkTier = new HashSet<NtwrkTier>();
            this.BnftPlanAccessCtl = new HashSet<BnftPlanAccessCtl>();
            this.Threshold = new HashSet<Threshold>();
            this.CvrgPhase = new HashSet<CvrgPhase>();
            this.FrmlryTier = new HashSet<FrmlryTier>();
            this.DAWCopay = new HashSet<DAWCopay>();
            this.Deducbl = new HashSet<Deducbl>();
            this.BnftPlanPharmType = new HashSet<BnftPlanPharmType>();
            this.PlanPrcg = new HashSet<PlanPrcg>();
            this.LICSSetup = new HashSet<LICSSetup>();
            this.FillExcp = new HashSet<FillExcp>();
            this.DeducblExcl = new HashSet<DeducblExcl>();
            this.CvrgSet = new HashSet<CvrgSet>();
            this.CopayOvrrd = new HashSet<CopayOvrrd>();
            this.EarlyRefillExcp = new HashSet<EarlyRefillExcp>();
            this.PlanCapLim = new HashSet<PlanCapLim>();
        }
    
        public long BnftPlanSK { get; set; }
        public long BnftPlanTypeSK { get; set; }
        public long LOBSK { get; set; }
        public Nullable<long> PrdctTypeSK { get; set; }
        public Nullable<long> PlanClsfcnTypeSK { get; set; }
        public Nullable<long> BnftPlanSizeClsfcnTypeSK { get; set; }
        public Nullable<long> PrescbrDrugOvrrdListSK { get; set; }
        public Nullable<long> AlwdPrescribersListSK { get; set; }
        public Nullable<long> FrmlrySK { get; set; }
        public Nullable<long> RxPrcgTypeSK { get; set; }
        public Nullable<long> DrugRefDbSK { get; set; }
        public Nullable<long> CopayFuncTypeSK { get; set; }
        public Nullable<long> CMSBnftStructTypeSK { get; set; }
        public string BnftPlanID { get; set; }
        public string BnftPlanName { get; set; }
        public string BnftPlanShortName { get; set; }
        public bool TmpltInd { get; set; }
        public string BnftPlanYr { get; set; }
        public bool EmbeddedDeductiblesInd { get; set; }
        public int NbrofNtwrkTiers { get; set; }
        public bool RejAllClaimsInd { get; set; }
        public bool AllowMnlEnrlmtInd { get; set; }
        public bool OnHIEInd { get; set; }
        public Nullable<decimal> DefaultVaccineAdmnstnFeeAmt { get; set; }
        public bool GrandfatheredPlanInd { get; set; }
        public bool AllowEmrgyFillsInd { get; set; }
        public bool COBRABnftOfferedInd { get; set; }
        public Nullable<int> MaxNbrofDaysAlwdonCOBRAAmt { get; set; }
        public string HIOSPlanVarntID { get; set; }
        public Nullable<int> NbrofFrmlryTiers { get; set; }
        public bool AllowMbrLocksInd { get; set; }
        public bool AllowTransitionFillsInd { get; set; }
        public Nullable<int> TransitionTimeframeDays { get; set; }
        public Nullable<int> TransitionLookBackPerDays { get; set; }
        public Nullable<int> LTCTransitionAlwdDays { get; set; }
        public Nullable<int> RtlTransitionAlwdDays { get; set; }
        public bool RestartTransitionatPlanYrInd { get; set; }
        public Nullable<byte> TransitionRestartMthNbr { get; set; }
        public bool MndtryGenrcDrugPlanInd { get; set; }
        public bool PrcsMcrPartBClaimsInd { get; set; }
        public Nullable<decimal> McrPartBCoinsurancePct { get; set; }
        public bool RequireSpcltyPharmforSpcltyDrugsInd { get; set; }
        public Nullable<decimal> McrCvrgGapGenrcPct { get; set; }
        public Nullable<decimal> McrCvrgGapBrandPct { get; set; }
        public Nullable<int> OneMthDaySuplAmt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
        public Nullable<decimal> LICS4DeducblAmt { get; set; }
        public Nullable<decimal> StdDeducblAmt { get; set; }
        public bool ExclPHIDataInReports { get; set; }
        public bool PayNonMcrPartDIngredients { get; set; }
        public bool InclNonMcrPartDonPDE { get; set; }
        public string BnftPlanAbbr { get; set; }
    
        public virtual AlwdPrescribersList AlwdPrescribersList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeducblEpsd> DeducblEpsd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeducblEpsd> DeducblEpsd1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanBnft> BnftPlanBnft { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBPBnftPlan> PBPBnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataCompareDtl> DataCompareDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanConfgPrpty> BnftPlanConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanWvrRider> BnftPlanWvrRider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NtwrkTier> NtwrkTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanAccessCtl> BnftPlanAccessCtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Threshold> Threshold { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CvrgPhase> CvrgPhase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryTier> FrmlryTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAWCopay> DAWCopay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deducbl> Deducbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanPharmType> BnftPlanPharmType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanPrcg> PlanPrcg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICSSetup> LICSSetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FillExcp> FillExcp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeducblExcl> DeducblExcl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CvrgSet> CvrgSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CopayOvrrd> CopayOvrrd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EarlyRefillExcp> EarlyRefillExcp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanCapLim> PlanCapLim { get; set; }
        public virtual BnftPlanSizeClsfcnType BnftPlanSizeClsfcnType { get; set; }
        public virtual BnftPlanType BnftPlanType { get; set; }
        public virtual CMSBnftStructType CMSBnftStructType { get; set; }
        public virtual CopayFuncType CopayFuncType { get; set; }
        public virtual DrugRefDb DrugRefDb { get; set; }
        public virtual Frmlry Frmlry { get; set; }
        public virtual LOB LOB { get; set; }
        public virtual PlanClsfcnType PlanClsfcnType { get; set; }
        public virtual PrdctType PrdctType { get; set; }
        public virtual PrescbrDrugOvrrdList PrescbrDrugOvrrdList { get; set; }
        public virtual RxPrcgType RxPrcgType { get; set; }
    }
}
