//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfgPrptyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfgPrptyType()
        {
            this.BnftConfgPrpty = new HashSet<BnftConfgPrpty>();
            this.BnftPlanConfgPrpty = new HashSet<BnftPlanConfgPrpty>();
            this.ConfgPrptyOpt = new HashSet<ConfgPrptyOpt>();
            this.PopGrpBnftPlanConfgPrpty = new HashSet<PopGrpBnftPlanConfgPrpty>();
            this.PBPConfgPrpty = new HashSet<PBPConfgPrpty>();
            this.PBPBnftPlanConfgPrpty = new HashSet<PBPBnftPlanConfgPrpty>();
            this.ConfgPrptyType1 = new HashSet<ConfgPrptyType>();
            this.PopGrpBnftPlanPkgConfgPrpty = new HashSet<PopGrpBnftPlanPkgConfgPrpty>();
        }
    
        public long ConfgPrptyTypeSK { get; set; }
        public long ConfgPrptyCatgTypeSK { get; set; }
        public Nullable<long> ConfgPrptyTypeParentSK { get; set; }
        public string ConfgPrptyTypeCode { get; set; }
        public string ConfgPrptyTypeDesc { get; set; }
        public int ConfgPrptyTypeDsplyPrity { get; set; }
        public string FldType { get; set; }
        public string DataType { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftConfgPrpty> BnftConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanConfgPrpty> BnftPlanConfgPrpty { get; set; }
        public virtual ConfgPrptyCatgType ConfgPrptyCatgType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfgPrptyOpt> ConfgPrptyOpt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpBnftPlanConfgPrpty> PopGrpBnftPlanConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBPConfgPrpty> PBPConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBPBnftPlanConfgPrpty> PBPBnftPlanConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfgPrptyType> ConfgPrptyType1 { get; set; }
        public virtual ConfgPrptyType ConfgPrptyType2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpBnftPlanPkgConfgPrpty> PopGrpBnftPlanPkgConfgPrpty { get; set; }
    }
}
