//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CopaySetup
    {
        public long CopaySetupSK { get; set; }
        public Nullable<long> NtwrkTierSK { get; set; }
        public Nullable<long> CvrgPhaseSK { get; set; }
        public Nullable<long> FrmlryTierSK { get; set; }
        public long CopayCoinsuranceLogicTypeSK { get; set; }
        public long BnftPlanPharmTypeDaySuplSK { get; set; }
        public Nullable<decimal> CopayAmt { get; set; }
        public Nullable<decimal> DlyRate { get; set; }
        public bool ApplyCopayInd { get; set; }
        public Nullable<decimal> CoinsurnacePct { get; set; }
        public Nullable<decimal> MaxMbrCostPerRx { get; set; }
        public Nullable<decimal> MbrMthlyCvrgMaxAmt { get; set; }
        public Nullable<decimal> MbrYearlyCvrgMaxAmt { get; set; }
        public Nullable<decimal> PlanMthlyCvrgMaxAmt { get; set; }
        public Nullable<decimal> PlanYearlyCvrgMaxAmt { get; set; }
        public bool MbrResponsibileforBrandGenrcCostDifferenceInd { get; set; }
        public bool ApplyBrandGenrcCostDifferencetoMOOPInd { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlanPharmTypeDaySupl BnftPlanPharmTypeDaySupl { get; set; }
        public virtual CopayCoinsuranceLogicType CopayCoinsuranceLogicType { get; set; }
        public virtual CvrgPhase CvrgPhase { get; set; }
        public virtual FrmlryTier FrmlryTier { get; set; }
        public virtual NtwrkTier NtwrkTier { get; set; }
    }
}
