//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrtriaDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CrtriaDtl()
        {
            this.CrtriaDtl1 = new HashSet<CrtriaDtl>();
        }
    
        public long CrtriaDtlSK { get; set; }
        public long CrtriaSetSK { get; set; }
        public Nullable<long> CrtriaOperTypeSK { get; set; }
        public long CrtriaCondTypeSK { get; set; }
        public long ValQulfrTypeSK { get; set; }
        public int CrtriaPrity { get; set; }
        public string CrtriaVal { get; set; }
        public string CrtriaDtlDesc { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
        public Nullable<long> CrtriaDtlParentSK { get; set; }
        public string CrtriaValMin { get; set; }
        public string CrtriaValMax { get; set; }
    
        public virtual CrtriaCondType CrtriaCondType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CrtriaDtl> CrtriaDtl1 { get; set; }
        public virtual CrtriaDtl CrtriaDtl2 { get; set; }
        public virtual CrtriaOperType CrtriaOperType { get; set; }
        public virtual CrtriaSet CrtriaSet { get; set; }
        public virtual ValQulfrType ValQulfrType { get; set; }
    }
}
