//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCompareDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataCompareDtl()
        {
            this.DataCompareMsg = new HashSet<DataCompareMsg>();
        }
    
        public long DataCompareDtlSK { get; set; }
        public long DataCompareHdrSK { get; set; }
        public Nullable<long> PopGrpPBPSK { get; set; }
        public Nullable<long> BnftPlanSK { get; set; }
        public string PlanPgmCode { get; set; }
        public string SysName { get; set; }
        public System.DateTime StartDt { get; set; }
        public Nullable<System.DateTime> CmpltDt { get; set; }
        public string AtlasXML { get; set; }
        public string SysXML { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataCompareMsg> DataCompareMsg { get; set; }
        public virtual DataCompareHdr DataCompareHdr { get; set; }
        public virtual PopGrpPBP PopGrpPBP { get; set; }
    }
}
