//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataCompareMsg
    {
        public long DataCompareMsgSK { get; set; }
        public long DataCompareDtlSK { get; set; }
        public string AtlasRecID { get; set; }
        public string ClsName { get; set; }
        public string FldName { get; set; }
        public string Msg { get; set; }
        public string AtlasVal { get; set; }
        public string SysVal { get; set; }
    
        public virtual DataCompareDtl DataCompareDtl { get; set; }
    }
}
