//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeducblEpsd
    {
        public long DeducblEpsdSK { get; set; }
        public long DeducblTypeSK { get; set; }
        public Nullable<long> PymtPrflDtlSK { get; set; }
        public long BnftPlanSK { get; set; }
        public Nullable<int> FreqQulfrTypeSK { get; set; }
        public Nullable<decimal> DeducblAmt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        public virtual BnftPlan BnftPlan1 { get; set; }
        public virtual DeducblType DeducblType { get; set; }
        public virtual FreqQulfrType FreqQulfrType { get; set; }
        public virtual PymtPrflDtl PymtPrflDtl { get; set; }
        public virtual DeducblType DeducblType1 { get; set; }
        public virtual FreqQulfrType FreqQulfrType1 { get; set; }
        public virtual PymtPrflDtl PymtPrflDtl1 { get; set; }
    }
}
