//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICSSetup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LICSSetup()
        {
            this.Deducbl = new HashSet<Deducbl>();
        }
    
        public long LICSSetupSK { get; set; }
        public long BnftPlanSK { get; set; }
        public long FrmlryTierSK { get; set; }
        public long CvrgPhaseSK { get; set; }
        public Nullable<long> LICSTypeSK { get; set; }
        public long CopayCoinsuranceLogicTypeSK { get; set; }
        public Nullable<decimal> CopayAmt { get; set; }
        public Nullable<decimal> CoinsurancePct { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
        public long DaySuplTypeSK { get; set; }
        public Nullable<long> PharmTypeSK { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        public virtual CopayCoinsuranceLogicType CopayCoinsuranceLogicType { get; set; }
        public virtual CvrgPhase CvrgPhase { get; set; }
        public virtual DaySuplType DaySuplType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deducbl> Deducbl { get; set; }
        public virtual FrmlryTier FrmlryTier { get; set; }
        public virtual PharmType PharmType { get; set; }
        public virtual LICSType LICSType { get; set; }
    }
}
