//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NtwrkTier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NtwrkTier()
        {
            this.BnftPlanBnftCvrgSetNtwrkTier = new HashSet<BnftPlanBnftCvrgSetNtwrkTier>();
            this.BnftPlanConfgPrpty = new HashSet<BnftPlanConfgPrpty>();
            this.CopaySetup = new HashSet<CopaySetup>();
            this.Deducbl = new HashSet<Deducbl>();
            this.NtwrkNtwrkTier = new HashSet<NtwrkNtwrkTier>();
            this.PBPBnftPlanConfgPrpty = new HashSet<PBPBnftPlanConfgPrpty>();
        }
    
        public long NtwrkTierSK { get; set; }
        public long BnftPlanSK { get; set; }
        public long NtwrkTierTypeSK { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanBnftCvrgSetNtwrkTier> BnftPlanBnftCvrgSetNtwrkTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BnftPlanConfgPrpty> BnftPlanConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CopaySetup> CopaySetup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deducbl> Deducbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NtwrkNtwrkTier> NtwrkNtwrkTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PBPBnftPlanConfgPrpty> PBPBnftPlanConfgPrpty { get; set; }
        public virtual NtwrkTierType NtwrkTierType { get; set; }
    }
}
