//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBPBnftPlanConfgPrpty
    {
        public long PBPBnftPlanConfgPrptySK { get; set; }
        public long ConfgPrptyTypeSK { get; set; }
        public Nullable<long> NtwrkTierSK { get; set; }
        public long PBPBnftPlanSK { get; set; }
        public string ConfgPrptyVal { get; set; }
        public string ConfgPrptyChildVal { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual ConfgPrptyType ConfgPrptyType { get; set; }
        public virtual NtwrkTier NtwrkTier { get; set; }
        public virtual PBPBnftPlan PBPBnftPlan { get; set; }
    }
}
