//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanPrcg
    {
        public long PlanPrcgSK { get; set; }
        public long DaySuplTypeSK { get; set; }
        public long BnftPlanSK { get; set; }
        public long PharmTypeSK { get; set; }
        public long CostBasisTypeSK { get; set; }
        public long DrugBrandTypeSK { get; set; }
        public Nullable<decimal> DiscPct { get; set; }
        public Nullable<decimal> DiscAmt { get; set; }
        public Nullable<decimal> MinDspnsgFeeAmt { get; set; }
        public Nullable<decimal> MaxDspnsgFeeAmt { get; set; }
        public Nullable<decimal> GERDspnsgFeeAmt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        public virtual CostBasisType CostBasisType { get; set; }
        public virtual DaySuplType DaySuplType { get; set; }
        public virtual DrugBrandType DrugBrandType { get; set; }
        public virtual PharmType PharmType { get; set; }
    }
}
