//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopGrpPBP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PopGrpPBP()
        {
            this.DataCompareDtl = new HashSet<DataCompareDtl>();
            this.PopGrpBnftPlan = new HashSet<PopGrpBnftPlan>();
            this.PopGrpBnftPlanPkgConfgPrpty = new HashSet<PopGrpBnftPlanPkgConfgPrpty>();
            this.PopGrpPBPStat = new HashSet<PopGrpPBPStat>();
            this.PopGrpPBPHealthcareFinclAcct = new HashSet<PopGrpPBPHealthcareFinclAcct>();
        }
    
        public long PopGrpPBPSK { get; set; }
        public long PopGrpSK { get; set; }
        public long PBPSK { get; set; }
        public string PlanPgmCode { get; set; }
        public bool AllowMnlEnrlmtInd { get; set; }
        public Nullable<byte> AccumtrRestartMth { get; set; }
        public Nullable<byte> AccumtrRestartDay { get; set; }
        public Nullable<System.DateTime> DOSProcsngStartDt { get; set; }
        public Nullable<System.DateTime> DOSProcsngEndDt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataCompareDtl> DataCompareDtl { get; set; }
        public virtual PBP PBP { get; set; }
        public virtual PopGrp PopGrp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpBnftPlan> PopGrpBnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpBnftPlanPkgConfgPrpty> PopGrpBnftPlanPkgConfgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpPBPStat> PopGrpPBPStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PopGrpPBPHealthcareFinclAcct> PopGrpPBPHealthcareFinclAcct { get; set; }
    }
}
