//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopGrpPBPHealthcareFinclAcct
    {
        public long PopGrpPBPHealthcareFinclAcctSK { get; set; }
        public long PopGrpPBPSK { get; set; }
        public long BnftPlanTypeSK { get; set; }
        public long HealthcareFinclAcctTypeSK { get; set; }
        public string BankName { get; set; }
        public string BankAcctNbr { get; set; }
        public Nullable<decimal> MaxContributionAmt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlanType BnftPlanType { get; set; }
        public virtual HealthcareFinclAcctType HealthcareFinclAcctType { get; set; }
        public virtual PopGrpPBP PopGrpPBP { get; set; }
    }
}
