//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescbrDrugOvrrdDtl
    {
        public long PrescbrDrugOvrrdDtlSK { get; set; }
        public long PrescbrSK { get; set; }
        public long PrescbrDrugOvrrdListSK { get; set; }
        public string NDC { get; set; }
        public string DrugLblName { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual Prescbr Prescbr { get; set; }
        public virtual PrescbrDrugOvrrdList PrescbrDrugOvrrdList { get; set; }
    }
}
