//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Threshold
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Threshold()
        {
            this.CvrgSetThreshold = new HashSet<CvrgSetThreshold>();
        }
    
        public long ThresholdSK { get; set; }
        public Nullable<long> BnftPlanSK { get; set; }
        public long ThresholdQulfrTypeSK { get; set; }
        public string ThresholdName { get; set; }
        public Nullable<int> ThresholdLimAmt { get; set; }
        public string RestartThresholdAtCalendarYr { get; set; }
        public string RestartThresholdAtPlanYr { get; set; }
        public Nullable<int> RestartThresholdAfterMbrEnrlmtDays { get; set; }
        public Nullable<int> RestartThresholdAfterMbrEnrlmtMths { get; set; }
        public Nullable<int> RestartThresholdAfterSvcDays { get; set; }
        public Nullable<int> RestartThresholdAfterSvcMths { get; set; }
        public Nullable<int> RestartThresholdAtBgnofCalendarMthNbr { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual BnftPlan BnftPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CvrgSetThreshold> CvrgSetThreshold { get; set; }
        public virtual ThresholdQulfrType ThresholdQulfrType { get; set; }
    }
}
