Ext.define('Atlas.plan.model.PlanGroupInfo', {
    extend: 'Atlas.common.model.Base',
    idProperty: 'planGroupId',
    fields: [
        {name: 'DrugDataSource', type: 'string', mapping: '@DrugDataSource'},
        {name: 'CMSCntrId', type: 'string'},
        {name: 'CMSFormularyId', type: 'string'},
        {name: 'CMSPlanId', type: 'string'},
        {name: 'CMSPlanType', type: 'string'},
        {name: 'MACListID', type: 'number'},
        {name: 'MbrCardBackCSS', type: 'string'},
        {name: 'MbrCardBackImage', type: 'string'},
        {name: 'MbrCardFrontCSS', type: 'string'},
        {name: 'MbrCardFrontImage', type: 'string'},
        {name: 'PDEPlanType', type: 'string'},
        {name: 'PayNonPartDIngredients', type: 'boolean'},
        {name: 'accountName', type: 'string'},
        {name: 'allowMedAdminFee', type: 'boolean'},
        {name: 'allowMemberLocks', type: 'boolean'},
        {name: 'asthmaHEDISAlert', type: 'boolean'},
        {name: 'benefitName', type: 'string'},
        {name: 'benefitStatus', type: 'string'},
        {name: 'carrierAcctNumber', type: 'string'},
        {name: 'carrierId', type: 'string'},
        {name: 'carrierName', type: 'string'},
        {name: 'carrierLOBId', type: 'number'},
        {name: 'cmsPBPid', type: 'string'},
        {name: 'copayCalcFunction', type: 'string'},
        {name: 'defMemberEnollAddrType', type: 'string'},
        {name: 'effDate', type: 'date' },
        {name: 'exclFormularyId', type: 'string'},
        {name: 'formularyId', type: 'string'},
        {name: 'licsSubsidy', type: 'boolean'},
        {name: 'lobName', type: 'string'},
        {name: 'mandatoryGeneric', type: 'boolean'},
        {name: 'medAdminFeeAmt', type: 'string'},
        {name: 'nonPrefPharmNetworkId', type: 'string'},
        {name: 'partBPCN', type: 'string'},
        {name: 'passThroughPricing', type: 'boolean'},
        {name: 'payablePatRespCodes', type: 'string'},
        {name: 'pcnCodeList', type: 'string'},
        {name: 'pharmNetworkId', type: 'number'},
        {name: 'planBenefitCode', type: 'string'},
        {name: 'planBenefitId', type: 'number'},
        {name: 'planFaxLogo', type: 'string'},
        {name: 'planGroupCode', type: 'string'},
        {name: 'planGroupId', type: 'string'},
        {name: 'planGroupName', type: 'string'},
        {name: 'planGroupStatus', type: 'string'},
        {name: 'processMTMCase', type: 'boolean'},
        {name: 'processMAPCase', type: 'boolean'},
        {name: 'renewalDate', type: 'date'},
        {name: 'termDate', type: 'date'},
        {name: 'useAllowedPrescribers', type: 'boolean'},
        {name: 'exclPHIInReports', type: 'boolean'},
        {name: 'includeNonPartDOnPDE', type: 'boolean'},
        {name: 'systemId', type: 'string', persist: false}
    ],
    proxy: {
        updateList: 'carrierId,carrierAcctNumber,carrierLOBId,planGroupCode,planGroupName,effDate,renewalDate,termDate,exclFormularyId,formularyId,MACListID,allowMemberLocks,processMTMCase,processMAPCase,pharmNetworkId,nonPrefPharmNetworkId,planFaxLogo,allowMedAdminFee,medAdminFeeAmt,payablePatRespCodes,partBPCN,pcnCodeList,mandatoryGeneric,cmsPBPid,CMSPlanId,CMSFormularyId,CMSCntrId,CMSPlanType,asthmaHEDISAlert,copayCalcFunction,defMemberEnollAddrType,MbrCardFrontImage,MbrCardFrontCSS,MbrCardBackImage,MbrCardBackCSS,PDEPlanType,useAllowedPrescribers,PayNonPartDIngredients,exclPHIInReports,includeNonPartDOnPDE,planGroupStatus',
        extraParams:{
            pFieldList: 'systemId,planGroupId,carrierId,carrierName,carrierAcctNumber,accountName,carrierLOBId,lobName,planGroupCode,planGroupName,effDate,renewalDate,termDate,planGroupStatus,exclFormularyId,formularyId,MACListID,allowMemberLocks,processMTMCase,processMAPCase,pharmNetworkId,nonPrefPharmNetworkId,planFaxLogo,allowMedAdminFee,medAdminFeeAmt,payablePatRespCodes,partBPCN,pcnCodeList,mandatoryGeneric,cmsPBPid,CMSPlanId,CMSFormularyId,CMSCntrId,CMSPlanType,asthmaHEDISAlert,copayCalcFunction,defMemberEnollAddrType,MbrCardFrontImage,MbrCardFrontCSS,MbrCardBackImage,MbrCardBackCSS,@DrugDataSource,PDEPlanType,useAllowedPrescribers,PayNonPartDIngredients,exclPHIInReports,includeNonPartDOnPDE'

        },
        url: 'plan/{0}/plangroupinfo'
    }
});
