var Atlas = Atlas || {};
Atlas.apiURL = 'http://apiqa.atlascomplete.local/atlas/';
Atlas.apidotnetURL = 'http://apiqa.atlascomplete.local/atlas/v2/';
Atlas.paymentURL = 'https://mo.paybill.com/V2/meridianhealthplan/login.aspx';
Atlas.paymentCallbackURL = 'http://qa.mhplan.local/portal/payment.php';
Atlas.nurseUrl = 'https://ssotest.mhplan.com/idp/startSSO.ping?PartnerSpId=mrdmemberssoua.axispointhealth.com';
Atlas.healthyHabitsUrl = 'https://uat-meridian.healthmedia.com/mhmsite?hash=f57aa3eef53137f242337eb51772333ebc5e953eec67ea837c89306c58b04280';
Atlas.patientUrl = 'https://ssotest.mhplan.com/idp/startSSO.ping?PartnerSpId=stgp360.concertohealth.com';
Atlas.docServiceNodeJS = "http://mindjs01-qvl.caidan.local:3000/api/merlinviewdoc";
Atlas.docServiceRESTRead = "http://mirxdb01-qvl.caidan.local/atlasrxshared/rest/atlasrxshared/getDocument";
Atlas.docServiceRESTUpdate = "http://mirxdb01-qvl.caidan.local/atlasrxshared/rest/atlasrxshared/setDocument";
Atlas.apiReportServiceURL = 'http://SQLRS2014Q2/ReportServer_INST02Q';
Atlas.apiReportURL = Atlas.apiReportServiceURL + '/Pages/ReportViewer.aspx';
