//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AHFSChangeList
    {
        public System.Guid BatchId { get; set; }
        public string AHFS_Id { get; set; }
        public string ChangeAction { get; set; }
        public string AHFS_NAME { get; set; }
        public string AHFS_ParentId { get; set; }
        public string PREV_AHFS_NAME { get; set; }
        public string PREV_AHFS_ParentId { get; set; }
    }
}
