//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ETC
    {
        public long ETC_ID { get; set; }
        public string ETC_NAME { get; set; }
        public Nullable<long> ETC_PARENT_ETC_ID { get; set; }
        public Nullable<System.Guid> BatchId { get; set; }
        public string ETC_NAME_ESP { get; set; }
    }
}
