//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDBDrugChangeList
    {
        public int DrugChangeListSK { get; set; }
        public string NDC { get; set; }
        public Nullable<System.Guid> BatchId { get; set; }
        public string ChangeAction { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> ETC_ID { get; set; }
        public string ETC_NAME { get; set; }
        public Nullable<int> HICL_SEQNO { get; set; }
        public string BrandName { get; set; }
        public string GCN_SEQNO { get; set; }
        public string LabelName { get; set; }
        public string MedId { get; set; }
        public string DrugType { get; set; }
        public Nullable<bool> OTC { get; set; }
        public string DrugStrength { get; set; }
        public string DosageForm { get; set; }
        public string RouteAdministration { get; set; }
        public Nullable<decimal> PackageSize { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public string GenericName { get; set; }
        public Nullable<int> GTC { get; set; }
        public string GTC_DESC { get; set; }
        public string AHFS { get; set; }
        public Nullable<long> NDCTypeSK { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PriceFedUprLimit { get; set; }
        public Nullable<decimal> PriceSugWhlUnit { get; set; }
        public Nullable<decimal> PriceSugWhlPkg { get; set; }
        public Nullable<decimal> PriceAWPUnit { get; set; }
        public Nullable<decimal> PriceAWPPkg { get; set; }
        public Nullable<decimal> PriceWACUnit { get; set; }
        public Nullable<decimal> PriceWACPkg { get; set; }
        public Nullable<bool> IsMaintDrug { get; set; }
        public Nullable<System.DateTime> DateToMarket { get; set; }
        public string DEA { get; set; }
        public string HCFA_FDA { get; set; }
        public string MSGenericIndicator { get; set; }
        public string GPI { get; set; }
        public Nullable<bool> FedRebateDrug { get; set; }
        public Nullable<System.DateTime> PriceAWPEffectiveDate { get; set; }
        public Nullable<System.DateTime> PriceWACEffectiveDate { get; set; }
        public Nullable<System.DateTime> PrevEffectiveDate { get; set; }
        public Nullable<System.DateTime> PrevDeletedDate { get; set; }
        public Nullable<int> PrevETC_ID { get; set; }
        public string PrevETC_NAME { get; set; }
        public Nullable<int> PrevHICL_SEQNO { get; set; }
        public string PrevBrandName { get; set; }
        public string PrevGCN_SEQNO { get; set; }
        public string PrevLabelName { get; set; }
        public string PrevMedId { get; set; }
        public string PrevDrugType { get; set; }
        public Nullable<bool> PrevOTC { get; set; }
        public string PrevDrugStrength { get; set; }
        public string PrevDosageForm { get; set; }
        public string PrevRouteAdministration { get; set; }
        public Nullable<decimal> PrevPackageSize { get; set; }
        public Nullable<bool> PrevIsObsolete { get; set; }
        public Nullable<System.DateTime> PrevObsoleteDate { get; set; }
        public string PrevGenericName { get; set; }
        public Nullable<int> PrevGTC { get; set; }
        public string PrevGTC_DESC { get; set; }
        public string PrevAHFS { get; set; }
        public Nullable<long> PrevNDCTypeSK { get; set; }
        public Nullable<decimal> PrevUnitPrice { get; set; }
        public Nullable<decimal> PrevPriceFedUprLimit { get; set; }
        public Nullable<decimal> PrevPriceSugWhlUnit { get; set; }
        public Nullable<decimal> PrevPriceSugWhlPkg { get; set; }
        public Nullable<decimal> PrevPriceAWPUnit { get; set; }
        public Nullable<decimal> PrevPriceAWPPkg { get; set; }
        public Nullable<decimal> PrevPriceWACUnit { get; set; }
        public Nullable<decimal> PrevPriceWACPkg { get; set; }
        public Nullable<bool> PrevIsMaintDrug { get; set; }
        public Nullable<System.DateTime> PrevDateToMarket { get; set; }
        public string PrevDEA { get; set; }
        public string PrevHCFA_FDA { get; set; }
        public Nullable<bool> PrevFedRebateDrug { get; set; }
        public string PrevMSGenericIndicator { get; set; }
        public string PrevGPI { get; set; }
        public Nullable<System.DateTime> PrevPriceAWPEffectiveDate { get; set; }
        public Nullable<System.DateTime> PrevPriceWACEffectiveDate { get; set; }
    }
}
