//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDBPECXRef
    {
        public long FDBClinicalDataXRefSK { get; set; }
        public string GCN_SEQNO { get; set; }
        public int PatEdCode { get; set; }
        public System.Guid BatchId { get; set; }
    }
}
