//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormularyCache
    {
        public long FormularyCacheSK { get; set; }
        public Nullable<long> FormularySK { get; set; }
        public string FormularyId { get; set; }
        public Nullable<int> FormularyVersion { get; set; }
        public string NDC { get; set; }
        public Nullable<int> ETC_ID { get; set; }
        public string ETC_NAME { get; set; }
        public string GPI { get; set; }
        public string GPIName { get; set; }
        public Nullable<int> HICL_SEQNO { get; set; }
        public string GenericName { get; set; }
        public string BrandName { get; set; }
        public string LabelName { get; set; }
        public string MedId { get; set; }
        public string DrugType { get; set; }
        public string OTC { get; set; }
        public string DrugStrength { get; set; }
        public string DosageForm { get; set; }
        public string RouteAdministration { get; set; }
        public string PackageSize { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public string GCN_SEQNO { get; set; }
        public Nullable<int> GTC { get; set; }
        public string GTC_DESC { get; set; }
        public string AHFS { get; set; }
        public Nullable<int> TierNbr { get; set; }
        public string IsCovered { get; set; }
        public Nullable<bool> IsOverrideGenericCheck { get; set; }
        public Nullable<bool> IsSpecialityDrug { get; set; }
        public Nullable<bool> IsRestrictToPkgSize { get; set; }
        public Nullable<bool> IsMedicareCarveOut { get; set; }
        public Nullable<bool> IsMedicaidFeeScreen { get; set; }
        public Nullable<bool> IsMaintenanceDrug { get; set; }
        public Nullable<int> ExtendedDaysSupply { get; set; }
        public Nullable<bool> IsPARequired { get; set; }
        public Nullable<int> PAAgeLimitMin { get; set; }
        public Nullable<int> PAAgeLimitMax { get; set; }
        public string PAAgeLimitType { get; set; }
        public string PAName { get; set; }
        public Nullable<bool> IsSTRequired { get; set; }
        public string STName { get; set; }
        public Nullable<int> MaxFillQty { get; set; }
        public Nullable<int> MaxFillPerPeriod { get; set; }
        public string MaxFillPeriodType { get; set; }
        public Nullable<int> QLFillQty { get; set; }
        public Nullable<int> QLFillPerPeriod { get; set; }
        public string QLFillPeriodType { get; set; }
        public Nullable<int> DaysSupplyFillQty { get; set; }
        public Nullable<int> DaysSupplyFillPerPeriod { get; set; }
        public string DaysSupplyPeriodType { get; set; }
        public string Gender { get; set; }
        public Nullable<int> AgeLimitMin { get; set; }
        public Nullable<int> AgeLimitMax { get; set; }
        public string AgeLimitType { get; set; }
        public Nullable<int> MaleAgeLimitMin { get; set; }
        public Nullable<int> MaleAgeLimitMax { get; set; }
        public string MaleAgeLimitType { get; set; }
        public Nullable<int> FemaleAgeLimitMin { get; set; }
        public Nullable<int> FemaleAgeLimitMax { get; set; }
        public string FemaleAgeLimitType { get; set; }
        public string PDLStatus { get; set; }
        public string PDFMessage { get; set; }
        public string UserNotes { get; set; }
        public Nullable<long> DrugCatgSK { get; set; }
        public Nullable<long> FrmlryTierSK { get; set; }
        public string CvrgPrptySummary { get; set; }
        public Nullable<System.DateTime> CacheUpdated { get; set; }
        public string HCFA_FDA { get; set; }
        public string DEA { get; set; }
        public Nullable<bool> IsFedRebateDrug { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DrugLists { get; set; }
    }
}
