//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrmlryReview
    {
        public long FrmlryReviewSK { get; set; }
        public long FrmlrySK { get; set; }
        public string NDC { get; set; }
        public Nullable<long> FrmlrySK_From { get; set; }
    }
}
