//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCNChangeList
    {
        public System.Guid BatchId { get; set; }
        public long GCN_SEQNO { get; set; }
        public Nullable<long> HICL_SEQNO { get; set; }
        public string GNN { get; set; }
        public string GNN60 { get; set; }
        public string ChangeAction { get; set; }
        public Nullable<long> PREV_HICL_SEQNO { get; set; }
        public string PREV_GNN { get; set; }
        public string PREV_GNN60 { get; set; }
    }
}
