//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedispanDrugChangeList
    {
        public long DrugChangeListSK { get; set; }
        public string NDC { get; set; }
        public System.Guid BatchId { get; set; }
        public string ChangeAction { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string GPI { get; set; }
        public string GPIName { get; set; }
        public string GenericName { get; set; }
        public string LabelName { get; set; }
        public Nullable<int> OTC { get; set; }
        public Nullable<int> IsObsolete { get; set; }
        public string RouteAdministration { get; set; }
        public string DosageForm { get; set; }
        public string DrugType { get; set; }
        public string AHFS { get; set; }
        public string DrugStrength { get; set; }
        public string PackageSize { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public Nullable<long> NDCTypeSK { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PriceFedUprLimit { get; set; }
        public Nullable<decimal> PriceSugWhlUnit { get; set; }
        public Nullable<decimal> PriceSugWhlPkg { get; set; }
        public Nullable<decimal> AWPUnitPrice { get; set; }
        public Nullable<decimal> AWPPackagePrice { get; set; }
        public Nullable<System.DateTime> AWPEffectiveDate { get; set; }
        public Nullable<decimal> WACUnitPrice { get; set; }
        public Nullable<decimal> WACPackagePrice { get; set; }
        public Nullable<System.DateTime> WACEffectiveDate { get; set; }
        public string MultiSourceCode { get; set; }
        public Nullable<bool> IsMaintDrug { get; set; }
        public Nullable<System.DateTime> DateToMarket { get; set; }
        public string DEA { get; set; }
        public string TEECode { get; set; }
        public Nullable<bool> FedRebateDrug { get; set; }
        public Nullable<int> ETC_ID { get; set; }
        public string ETC_Name { get; set; }
        public Nullable<int> HICL_SEQNO { get; set; }
        public string BrandName { get; set; }
        public string GCN_SEQNO { get; set; }
        public string MedId { get; set; }
        public Nullable<int> GTC { get; set; }
        public string GTC_DESC { get; set; }
        public Nullable<System.DateTime> PrevEffectiveDate { get; set; }
        public string PrevGPI { get; set; }
        public string PrevGPIName { get; set; }
        public string PrevGenericName { get; set; }
        public string PrevLabelName { get; set; }
        public Nullable<int> PrevOTC { get; set; }
        public Nullable<int> PrevIsObsolete { get; set; }
        public string PrevRouteAdministration { get; set; }
        public string PrevDosageForm { get; set; }
        public string PrevDrugType { get; set; }
        public string PrevAHFS { get; set; }
        public string PrevDrugStrength { get; set; }
        public string PrevPackageSize { get; set; }
        public Nullable<System.DateTime> PrevObsoleteDate { get; set; }
        public Nullable<long> PrevNDCTypeSK { get; set; }
        public Nullable<decimal> PrevUnitPrice { get; set; }
        public Nullable<decimal> PrevPriceFedUprLimit { get; set; }
        public Nullable<decimal> PrevPriceSugWhlUnit { get; set; }
        public Nullable<decimal> PrevPriceSugWhlPkg { get; set; }
        public Nullable<decimal> PrevAWPUnitPrice { get; set; }
        public Nullable<decimal> PrevAWPPackagePrice { get; set; }
        public Nullable<System.DateTime> PrevAWPEffectiveDate { get; set; }
        public Nullable<decimal> PrevWACUnitPrice { get; set; }
        public Nullable<decimal> PrevWACPackagePrice { get; set; }
        public Nullable<System.DateTime> PrevWACEffectiveDate { get; set; }
        public string PrevMultiSourceCode { get; set; }
        public Nullable<bool> PrevIsMaintDrug { get; set; }
        public Nullable<System.DateTime> PrevDateToMarket { get; set; }
        public string PrevDEA { get; set; }
        public string PrevTEECode { get; set; }
        public Nullable<bool> PrevFedRebateDrug { get; set; }
        public Nullable<int> PrevETC_ID { get; set; }
        public string PrevETC_Name { get; set; }
        public Nullable<int> PrevHICL_SEQNO { get; set; }
        public string PrevBrandName { get; set; }
        public string PrevGCN_SEQNO { get; set; }
        public string PrevMedId { get; set; }
        public Nullable<int> PrevGTC { get; set; }
        public string PrevGTC_DESC { get; set; }
    }
}
