//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedispanDrugList
    {
        public string NDC { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string GPI { get; set; }
        public string GPIName { get; set; }
        public string GenericName { get; set; }
        public string LabelName { get; set; }
        public Nullable<bool> OTC { get; set; }
        public Nullable<bool> IsObsolete { get; set; }
        public string RouteAdministration { get; set; }
        public string DosageForm { get; set; }
        public string DrugType { get; set; }
        public string AHFS { get; set; }
        public string DrugStrength { get; set; }
        public string PackageSize { get; set; }
        public Nullable<System.DateTime> ObsoleteDate { get; set; }
        public Nullable<long> NDCTypeSK { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> PriceFedUprLimit { get; set; }
        public Nullable<decimal> PriceSugWhlUnit { get; set; }
        public Nullable<decimal> PriceSugWhlPkg { get; set; }
        public Nullable<decimal> AWPUnitPrice { get; set; }
        public Nullable<decimal> AWPPackagePrice { get; set; }
        public Nullable<System.DateTime> AWPEffectiveDate { get; set; }
        public Nullable<decimal> WACUnitPrice { get; set; }
        public Nullable<decimal> WACPackagePrice { get; set; }
        public Nullable<System.DateTime> WACEffectiveDate { get; set; }
        public string MultiSourceCode { get; set; }
        public Nullable<bool> IsMaintDrug { get; set; }
        public Nullable<System.DateTime> DateToMarket { get; set; }
        public string DEA { get; set; }
        public string TEECode { get; set; }
        public Nullable<bool> FedRebateDrug { get; set; }
        public Nullable<System.Guid> BatchId { get; set; }
        public Nullable<bool> IsNewDrug { get; set; }
        public Nullable<int> ETC_ID { get; set; }
        public string ETC_Name { get; set; }
        public Nullable<int> HICL_SEQNO { get; set; }
        public string BrandName { get; set; }
        public string GCN_SEQNO { get; set; }
        public string MedId { get; set; }
        public Nullable<int> GTC { get; set; }
        public string GTC_DESC { get; set; }
        public Nullable<System.DateTime> MarketStartDate { get; set; }
        public Nullable<System.DateTime> MarketEndDate { get; set; }
        public string MarketCategory { get; set; }
    }
}
