//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSDrugType
    {
        public long MSDrugTypeSK { get; set; }
        public bool OTCInd { get; set; }
        public decimal BeginPctVal { get; set; }
        public decimal EndPctVal { get; set; }
        public string DrugType { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LasMofdBy { get; set; }
        public System.DateTimeOffset LastMofdTs { get; set; }
    }
}
