//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFMessage
    {
        public long PDFMessageSK { get; set; }
        public string PDFMessage1 { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
    }
}
