//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFmtSection
    {
        public long RptFmtSectionSK { get; set; }
        public long RptFmtSK { get; set; }
        public int SectionNbr { get; set; }
        public string SectionTitle { get; set; }
        public string SectionContents { get; set; }
    }
}
