//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SumRptCfg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SumRptCfg()
        {
            this.SumRptCfgCol = new HashSet<SumRptCfgCol>();
            this.SumRptCfgCvrgPrptyType = new HashSet<SumRptCfgCvrgPrptyType>();
            this.SumRptCfgSctn = new HashSet<SumRptCfgSctn>();
            this.SumRptCfgTier = new HashSet<SumRptCfgTier>();
        }
    
        public long SumRptCfgSK { get; set; }
        public string SumRptCfgName { get; set; }
        public string SumRptCfgDesc { get; set; }
        public Nullable<long> FileFmtSK { get; set; }
        public Nullable<long> LangSK { get; set; }
        public Nullable<long> FontSizeSK { get; set; }
        public Nullable<bool> InclUMInd { get; set; }
        public Nullable<bool> InclNotCvrdInd { get; set; }
        public Nullable<long> TierDisplSK { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumRptCfgCol> SumRptCfgCol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumRptCfgCvrgPrptyType> SumRptCfgCvrgPrptyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumRptCfgSctn> SumRptCfgSctn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SumRptCfgTier> SumRptCfgTier { get; set; }
    }
}
