//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpCustomNDC
    {
        public string NDC { get; set; }
        public string LN { get; set; }
        public string GCN_SeqNo { get; set; }
        public Nullable<int> Hicl_SeqNo { get; set; }
        public Nullable<int> ETCId { get; set; }
        public string ETCName { get; set; }
        public Nullable<int> NPT_TYPE { get; set; }
        public Nullable<System.DateTime> NPT_DATEC { get; set; }
        public Nullable<decimal> NPT_PRICEX { get; set; }
    }
}
