//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Reference.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpUserDrugListDtlPage
    {
        public int UserRowId { get; set; }
        public string UserId { get; set; }
        public int RowId { get; set; }
        public Nullable<long> DrugListDtlSK { get; set; }
        public string DrugListDtlName { get; set; }
        public Nullable<int> NDCCount { get; set; }
        public Nullable<long> DrugListSK { get; set; }
        public Nullable<System.Guid> SessionId { get; set; }
    }
}
