//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public long AlertSK { get; set; }
        public long AlertTypeSK { get; set; }
        public Nullable<long> UserGrpSK { get; set; }
        public string AlertDesc { get; set; }
        public string ActnVal { get; set; }
        public string AcknowledgedBy { get; set; }
        public Nullable<System.DateTime> AcknowledgedDt { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual AlertType AlertType { get; set; }
        public virtual UserGrp UserGrp { get; set; }
    }
}
