//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aprvl
    {
        public long AprvlSK { get; set; }
        public long AprvdByUserSK { get; set; }
        public Nullable<long> DrugListSK { get; set; }
        public Nullable<long> FrmlrySK { get; set; }
        public long AprvlTypeSK { get; set; }
        public Nullable<System.DateTimeOffset> SubmtdTs { get; set; }
        public string AprvlNotes { get; set; }
        public string SubmtdBy { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        public virtual AprvlType AprvlType { get; set; }
        public virtual DrugList DrugList { get; set; }
        public virtual Frmlry Frmlry { get; set; }
        public virtual User User { get; set; }
    }
}
