//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugCatg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugCatg()
        {
            this.DrugCatgCvrgPrpty = new HashSet<DrugCatgCvrgPrpty>();
            this.DrugCatgCrtriaGrp = new HashSet<DrugCatgCrtriaGrp>();
        }
    
        public long DrugCatgSK { get; set; }
        public long FrmlrySK { get; set; }
        public Nullable<long> FrmlryTierSK { get; set; }
        public string DrugCatgName { get; set; }
        public bool CvrdInd { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugCatgCvrgPrpty> DrugCatgCvrgPrpty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugCatgCrtriaGrp> DrugCatgCrtriaGrp { get; set; }
        public virtual Frmlry Frmlry { get; set; }
        public virtual FrmlryTier FrmlryTier { get; set; }
    }
}
