//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DrugList()
        {
            this.Aprvl = new HashSet<Aprvl>();
            this.DrugListAccessCtl = new HashSet<DrugListAccessCtl>();
            this.FrmlryDrugList = new HashSet<FrmlryDrugList>();
            this.DrugListDtl = new HashSet<DrugListDtl>();
        }
    
        public long DrugListSK { get; set; }
        public Nullable<long> LOBSK { get; set; }
        public long DrugRefDbSK { get; set; }
        public string DrugListName { get; set; }
        public int DrugPostObsltAlwdDays { get; set; }
        public bool AutomaticallyAssignNewNDCsInd { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aprvl> Aprvl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugListAccessCtl> DrugListAccessCtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryDrugList> FrmlryDrugList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugListDtl> DrugListDtl { get; set; }
        public virtual DrugRefDb DrugRefDb { get; set; }
        public virtual LOB LOB { get; set; }
    }
}
