//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frmlry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Frmlry()
        {
            this.Aprvl = new HashSet<Aprvl>();
            this.DrugCatg = new HashSet<DrugCatg>();
            this.FrmlryAccessCtl = new HashSet<FrmlryAccessCtl>();
            this.FrmlryStat = new HashSet<FrmlryStat>();
            this.FrmlryDrugList = new HashSet<FrmlryDrugList>();
            this.FrmlryTier = new HashSet<FrmlryTier>();
            this.FrmlryConfgPrpty = new HashSet<FrmlryConfgPrpty>();
            this.FrmlryNotes = new HashSet<FrmlryNotes>();
            this.PAPgm = new HashSet<PAPgm>();
        }
    
        public long FrmlrySK { get; set; }
        public long LOBSK { get; set; }
        public long DrugThrputcClsTypeSK { get; set; }
        public long DrugRefDbSK { get; set; }
        public Nullable<int> DrugPostObsltAlwdDays { get; set; }
        public string FrmlryName { get; set; }
        public string FrmlryID { get; set; }
        public int FrmlryVer { get; set; }
        public Nullable<bool> AutomaticallyAssignNewNDCsInd { get; set; }
        public System.DateTime EfctvStartDt { get; set; }
        public System.DateTime EfctvEndDt { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public System.DateTimeOffset LastModfdTs { get; set; }
        public Nullable<System.DateTimeOffset> InctvTs { get; set; }
        public Nullable<System.DateTimeOffset> DelTs { get; set; }
        public Nullable<long> SumryRptConfgSK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aprvl> Aprvl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DrugCatg> DrugCatg { get; set; }
        public virtual DrugRefDb DrugRefDb { get; set; }
        public virtual DrugThrputcClsType DrugThrputcClsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryAccessCtl> FrmlryAccessCtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryStat> FrmlryStat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryDrugList> FrmlryDrugList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryTier> FrmlryTier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryConfgPrpty> FrmlryConfgPrpty { get; set; }
        public virtual LOB LOB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrmlryNotes> FrmlryNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAPgm> PAPgm { get; set; }
    }
}
