//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrmlryNotes
    {
        public long FrmlryNoteSK { get; set; }
        public long FrmlrySK { get; set; }
        public long AprvlTypeSK { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTimeOffset CreatedTs { get; set; }
        public string LastModfdBy { get; set; }
        public Nullable<System.DateTimeOffset> LastModfdTs { get; set; }
        public string Subject { get; set; }
    
        public virtual AprvlType AprvlType { get; set; }
        public virtual Frmlry Frmlry { get; set; }
    }
}
