//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Formulary.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDrugCatgCvrgPrpty
    {
        public long DrugCatgSK { get; set; }
        public long FrmlrySK { get; set; }
        public Nullable<long> FrmlryTierSK { get; set; }
        public string DrugCatgName { get; set; }
        public Nullable<int> TierNbr { get; set; }
        public string IsCovered { get; set; }
        public string IsOverrideGenericCheck { get; set; }
        public string IsSpecialityDrug { get; set; }
        public string IsRestrictToPkgSize { get; set; }
        public string IsMedicareCarveOut { get; set; }
        public string IsMedicaidFeeScreen { get; set; }
        public string IsMaintenanceDrug { get; set; }
        public string ExtendedDaysSupply { get; set; }
        public int IsPARequired { get; set; }
        public string PAAgeLimitMin { get; set; }
        public string PAAgeLimitMax { get; set; }
        public string PAAgeLimitType { get; set; }
        public string PAName { get; set; }
        public int IsSTRequired { get; set; }
        public string STName { get; set; }
        public string MaxFillQty { get; set; }
        public string MaxFillPerPeriod { get; set; }
        public Nullable<long> MaxFillPeriodType { get; set; }
        public string QLFillQty { get; set; }
        public string QLFillPerPeriod { get; set; }
        public string QLFillPeriodType { get; set; }
        public string DaysSupplyFillQty { get; set; }
        public string DaysSupplyFillPerPeriod { get; set; }
        public string DaysSupplyPeriodType { get; set; }
        public string Gender { get; set; }
        public string AgeLimitMin { get; set; }
        public string AgeLimitMax { get; set; }
        public string AgeLimitType { get; set; }
        public string MaleAgeLimitMin { get; set; }
        public string MaleAgeLimitMax { get; set; }
        public string MaleAgeLimitType { get; set; }
        public string FemaleAgeLimitMin { get; set; }
        public string FemaleAgeLimitMax { get; set; }
        public string FemaleAgeLimitType { get; set; }
        public string PDFMessage { get; set; }
        public string PDLStatus { get; set; }
        public string UserNotes { get; set; }
        public string CvrgPrptySummary { get; set; }
    }
}
