/**
 * Created by b6636 on 11/29/2016.
 */
Ext.define('Atlas.portals.provider.model.ProviderClaimSearchResult', {
    extend: 'Atlas.common.model.Base',
    //extend: 'Atlas.common.model.StaticBase',
    fields: [
        "obvisits",
        {
            name: "obvisitsText",
            calculate: function (data) {
                if (data.obvisits && Ext.isArray(data.obvisits)) {
                    return data.obvisits.join('|');
                }
            }
        },
        "billProvId",
        "nonCoveredDays",
        "otherInsPaidAmt",
        "faclId",
        "otherProvId",
        "controlNum",
        "acceptAssignment",
        "faclCity",
        "resubmitCode",
        "otherProvNpi",
        "claimStatusDesc",
        "otherInsGender",
        "coveredDays",
        "formType",
        "attProvId",
        "diagCd2",
        "diagCd3",
        "disabledThru",
        "diagCd1",
        "disabledFrom",
        "diagCd6",
        "diagCd7",
        "diagCd4",
        "surgProcDate",
        "referprovnpi",
        "eobSentDate",
        "diagCd5",
        "diagCd8",
        "diagCd9",
        "otherInsMI",
        "totalCharge",
        "condOther",
        "lmpDate",
        {name:"stmtFromDate", type:"date", dateFormat: 'Y-m-d'},
        "lifeResDays",
        "otherInsFirstName",
        "admitDate",
        "planID",
        "servLocID",
        "paidAmount",
        "faclState",
        "diagCdQual19",
        "diagCdQual18",
        "systemID",
        "HDolEmailSendDt",
        "diagCdQual17",
        "diagCdQual16",
        "admitHour",
        "dischargeStatus",
        "memberName",
        "HDolMessage",
        "origRefnum",
        "ptnEmploymentStatus",
        "serviceprovtaxonomy",
        "pos",
        "dateReceived",
        "spanFromDate",
        "diagCdQual22",
        "diagCdQual21",
        "diagCdQual20",
        "diagCdQual25",
        "fedTaxId",
        "diagCdQual24",
        "diagCdQual23",
        "valueAmt",
        "drgCode",
        "attprovnpi",
        "facilitystate",
        "diagCdQual9",
        "diagCdQual7",
        "diagCdQual8",
        "referProvId",
        "diagCdQual5",
        "freqCode",
        "diagCdQual6",
        "diagCdQual3",
        "dbRowID",
        "diagCdQual4",
        "diagCdQual1",
        "diagCdQual2",
        "servProvId",
        "eobSent",
        "autoState",
        "processStatus",
        "servprovnpi",
        "vendorId",
        "otherInsEmployer",
        "injuryDate",
        "faclProvId",
        "admitType",
        "dischargeHour",
        "facilitycity",
        "wrdIdx",
        "occurCodes",
        "vendorLocId",
        "otherInsPlan",
        "ptnAccountNum",
        "totalPaid",
        "otherInsEstAmtDue",
        "faclAddress2",
        "faclAddress1",
        "valueCode",
        "condCodes",
        "vendorName",
        "dispMemberID",
        "condEmployment",
        "otherInsPolicy",
        "rowNUm",
        "diagCdQual11",
        "recipientID",
        "diagCdQual10",
        "diagCdQual15",
        "diagCdQual14",
        "illnessDate",
        "icControlNum",
        "diagCdQual13",
        "lobID",
        "diagCdQual12",
        "priorAuthNum",
        "HDolSendBy",
        "coinsDays",
        "admitDiagCd",
        "facilitynpi",
        "condAuto",
        "admitSource",
        "dischargeDate",
        "stmtThruDate",
        "diagCd23",
        "diagCd22",
        "otherInsurance",
        "diagCd25",
        "otherpayername",
        "diagCd24",
        "ptnMaritalStatus",
        "claimNumber",
        "diagCd21",
        "diagCd20",
        "diagCd19",
        "taxIdInd",
        "diagCd16",
        "balanceDue",
        "diagCd15",
        "diagCd18",
        "billType",
        "diagCd17",
        "firstIllnessDate",
        "billprovnpi",
        "otherInsDob",
        "medicalRecordNum",
        "occurDates",
        "spanCodes",
        "surgProcCode",
        "otherInsLastName",
        "servProvName",
        "spanThruDate",
        "faclName",
        "diagCd12",
        "diagCd11",
        "faclZip",
        "diagCd14",
        "diagCd13",
        "diagCd10",
        "remarks",
        "adjrsncode"
    ],

    proxy: {
        //url: 'resources/data/dummydata/portals/provider/institutionalClaim.json'
        url: 'provider/hp/claimheadermasterweb',
        extraParams: {
            "pRowID": 0,
            "pRowNum": 1,
            "pRows": 9999,
            "pagination": true
        }
        // "pWhere": "ServProvID = 47986 and stmtFromDate >= '10/15/2016' and stmtFromDate <= '11/29/2016'|1|25",
        // "pSort": "claimNumber desc"
    }
});