//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.BenefitPlan.DAL.EDIMerlinService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:soap-fault:details")]
    public partial class FaultDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:hpmich-local-EDIMerlin", ConfigurationName="EDIMerlinService.EDIMerlinObj")]
    public interface EDIMerlinObj {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Atlas.BenefitPlan.DAL.EDIMerlinService.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranResponse applyaccumtran(Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranResponse> applyaccumtranAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Atlas.BenefitPlan.DAL.EDIMerlinService.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeResponse getEnrollmentbyGroupCode(Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeResponse> getEnrollmentbyGroupCodeAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Atlas.BenefitPlan.DAL.EDIMerlinService.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsResponse loadExternalAccumulators(Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsResponse> loadExternalAccumulatorsAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Atlas.BenefitPlan.DAL.EDIMerlinService.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceResponse loadMedicalOOPBalance(Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceResponse> loadMedicalOOPBalanceAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Atlas.BenefitPlan.DAL.EDIMerlinService.FaultDetail), Action="", Name="FaultDetail", Namespace="urn:soap-fault:details")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanResponse getXMLOutputForPlan(Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanResponse> getXMLOutputForPlanAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyaccumtran", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class applyaccumtranRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pTransaction;
        
        public applyaccumtranRequest() {
        }
        
        public applyaccumtranRequest(string pTransaction) {
            this.pTransaction = pTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyaccumtranResponse", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class applyaccumtranResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pResult;
        
        public applyaccumtranResponse() {
        }
        
        public applyaccumtranResponse(string result, string pResult) {
            this.result = result;
            this.pResult = pResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnrollmentbyGroupCode", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class getEnrollmentbyGroupCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string progGroupCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string progBenefitCode;
        
        public getEnrollmentbyGroupCodeRequest() {
        }
        
        public getEnrollmentbyGroupCodeRequest(string progGroupCode, string progBenefitCode) {
            this.progGroupCode = progGroupCode;
            this.progBenefitCode = progBenefitCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEnrollmentbyGroupCodeResponse", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class getEnrollmentbyGroupCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string planGroupCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> carrierId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string planBenefitCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pProgramStatus;
        
        public getEnrollmentbyGroupCodeResponse() {
        }
        
        public getEnrollmentbyGroupCodeResponse(string result, string planGroupCode, System.Nullable<int> carrierId, string planBenefitCode, string pProgramStatus) {
            this.result = result;
            this.planGroupCode = planGroupCode;
            this.carrierId = carrierId;
            this.planBenefitCode = planBenefitCode;
            this.pProgramStatus = pProgramStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadExternalAccumulators", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class loadExternalAccumulatorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ipiSystemId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pRequest;
        
        public loadExternalAccumulatorsRequest() {
        }
        
        public loadExternalAccumulatorsRequest(System.Nullable<int> ipiSystemId, string pRequest) {
            this.ipiSystemId = ipiSystemId;
            this.pRequest = pRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadExternalAccumulatorsResponse", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class loadExternalAccumulatorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pMessage;
        
        public loadExternalAccumulatorsResponse() {
        }
        
        public loadExternalAccumulatorsResponse(string result, string pResponse, System.Nullable<int> pResult, string pMessage) {
            this.result = result;
            this.pResponse = pResponse;
            this.pResult = pResult;
            this.pMessage = pMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadMedicalOOPBalance", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class loadMedicalOOPBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pRequest;
        
        public loadMedicalOOPBalanceRequest() {
        }
        
        public loadMedicalOOPBalanceRequest(string pRequest) {
            this.pRequest = pRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="loadMedicalOOPBalanceResponse", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class loadMedicalOOPBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pMessage;
        
        public loadMedicalOOPBalanceResponse() {
        }
        
        public loadMedicalOOPBalanceResponse(string result, string pResponse, System.Nullable<int> pResult, string pMessage) {
            this.result = result;
            this.pResponse = pResponse;
            this.pResult = pResult;
            this.pMessage = pMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLOutputForPlan", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class getXMLOutputForPlanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pSessionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pAtlasRecordId;
        
        public getXMLOutputForPlanRequest() {
        }
        
        public getXMLOutputForPlanRequest(string pSessionID, string pAtlasRecordId) {
            this.pSessionID = pSessionID;
            this.pAtlasRecordId = pAtlasRecordId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLOutputForPlanResponse", WrapperNamespace="urn:hpmich-local-EDIMerlin:EDIMerlin", IsWrapped=true)]
    public partial class getXMLOutputForPlanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pDataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> pResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:hpmich-local-EDIMerlin:EDIMerlin", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string pMessage;
        
        public getXMLOutputForPlanResponse() {
        }
        
        public getXMLOutputForPlanResponse(string result, string pDataXML, System.Nullable<int> pResult, string pMessage) {
            this.result = result;
            this.pDataXML = pDataXML;
            this.pResult = pResult;
            this.pMessage = pMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EDIMerlinObjChannel : Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EDIMerlinObjClient : System.ServiceModel.ClientBase<Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj>, Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj {
        
        public EDIMerlinObjClient() {
        }
        
        public EDIMerlinObjClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EDIMerlinObjClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDIMerlinObjClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EDIMerlinObjClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranResponse Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj.applyaccumtran(Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest request) {
            return base.Channel.applyaccumtran(request);
        }
        
        public string applyaccumtran(string pTransaction, out string pResult) {
            Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest inValue = new Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest();
            inValue.pTransaction = pTransaction;
            Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranResponse retVal = ((Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj)(this)).applyaccumtran(inValue);
            pResult = retVal.pResult;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranResponse> applyaccumtranAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.applyaccumtranRequest request) {
            return base.Channel.applyaccumtranAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeResponse Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj.getEnrollmentbyGroupCode(Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest request) {
            return base.Channel.getEnrollmentbyGroupCode(request);
        }
        
        public string getEnrollmentbyGroupCode(string progGroupCode, string progBenefitCode, out string planGroupCode, out System.Nullable<int> carrierId, out string planBenefitCode, out string pProgramStatus) {
            Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest inValue = new Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest();
            inValue.progGroupCode = progGroupCode;
            inValue.progBenefitCode = progBenefitCode;
            Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeResponse retVal = ((Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj)(this)).getEnrollmentbyGroupCode(inValue);
            planGroupCode = retVal.planGroupCode;
            carrierId = retVal.carrierId;
            planBenefitCode = retVal.planBenefitCode;
            pProgramStatus = retVal.pProgramStatus;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeResponse> getEnrollmentbyGroupCodeAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.getEnrollmentbyGroupCodeRequest request) {
            return base.Channel.getEnrollmentbyGroupCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsResponse Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj.loadExternalAccumulators(Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest request) {
            return base.Channel.loadExternalAccumulators(request);
        }
        
        public string loadExternalAccumulators(System.Nullable<int> ipiSystemId, string pRequest, out string pResponse, out System.Nullable<int> pResult, out string pMessage) {
            Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest inValue = new Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest();
            inValue.ipiSystemId = ipiSystemId;
            inValue.pRequest = pRequest;
            Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsResponse retVal = ((Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj)(this)).loadExternalAccumulators(inValue);
            pResponse = retVal.pResponse;
            pResult = retVal.pResult;
            pMessage = retVal.pMessage;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsResponse> loadExternalAccumulatorsAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.loadExternalAccumulatorsRequest request) {
            return base.Channel.loadExternalAccumulatorsAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceResponse Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj.loadMedicalOOPBalance(Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest request) {
            return base.Channel.loadMedicalOOPBalance(request);
        }
        
        public string loadMedicalOOPBalance(string pRequest, out string pResponse, out System.Nullable<int> pResult, out string pMessage) {
            Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest inValue = new Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest();
            inValue.pRequest = pRequest;
            Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceResponse retVal = ((Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj)(this)).loadMedicalOOPBalance(inValue);
            pResponse = retVal.pResponse;
            pResult = retVal.pResult;
            pMessage = retVal.pMessage;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceResponse> loadMedicalOOPBalanceAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.loadMedicalOOPBalanceRequest request) {
            return base.Channel.loadMedicalOOPBalanceAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanResponse Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj.getXMLOutputForPlan(Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest request) {
            return base.Channel.getXMLOutputForPlan(request);
        }
        
        public string getXMLOutputForPlan(string pSessionID, string pAtlasRecordId, out string pDataXML, out System.Nullable<int> pResult, out string pMessage) {
            Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest inValue = new Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest();
            inValue.pSessionID = pSessionID;
            inValue.pAtlasRecordId = pAtlasRecordId;
            Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanResponse retVal = ((Atlas.BenefitPlan.DAL.EDIMerlinService.EDIMerlinObj)(this)).getXMLOutputForPlan(inValue);
            pDataXML = retVal.pDataXML;
            pResult = retVal.pResult;
            pMessage = retVal.pMessage;
            return retVal.result;
        }
        
        public System.Threading.Tasks.Task<Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanResponse> getXMLOutputForPlanAsync(Atlas.BenefitPlan.DAL.EDIMerlinService.getXMLOutputForPlanRequest request) {
            return base.Channel.getXMLOutputForPlanAsync(request);
        }
    }
}
