Ext.define('Atlas.member.model.MemLocksPrescriber', {
    extend: 'Atlas.common.model.Base',
    fields: [
        {name: 'systemID', type: 'number'},
        {name: 'currentLockID', type: 'string'},
        {name: 'carrierID', type: 'int'},
        {name: 'parentSystemID', type: 'int'},
        {name: 'newLockID', type: 'string'},
        {name: 'recipientID', type: 'number'},
        {name: 'Account', type: 'string'},
        {name: 'currentStatus', type: 'string'},
        {name: 'toBeStatus', type: 'string'},
        {name: 'LOB', type: 'string'},
        {name: 'action', type: 'string'},
        {name: 'Carrier', type: 'string'},
        {name: 'officeContact', type: 'string'},
        {name: 'officeContactPhone', type: 'string'},
        {name: 'planContactName', type: 'string'},
        {name: 'planContactExtn', type: 'number'},
        {name: 'planContactJobDesc', type: 'string'},
        {name: 'plangroupId', type: 'int'},
        {name: 'memberID', type: 'string'},
        {name: 'wfirst', type: 'string'},
        {name: 'wlast', type: 'string'},
        {name: 'waddress1', type: 'string'},
        {name: 'waddress2', type: 'string'},
        {name: 'wcity', type: 'string'},
        {name: 'wstate', type: 'string'},
        {name: 'wzip', type: 'string'},
        {name: 'wsort', type: 'string'},
        {name: 'lockName', type: 'string'},
        {name: 'lockType', type: 'string'},
        {name: 'lockAddress1', type: 'string'},
        {name: 'lockAddress2', type: 'string'},
        {name: 'lockCity', type: 'string'},
        {name: 'lockState', type: 'string'},
        {name: 'lockzip', type: 'string'},
        {name: 'createdBy', type: 'string'},
        {name: 'createdDate', type: 'date'},
        {name: 'approvedBy', type: 'string'},
        {name: 'approvalDate', type: 'date'},
        {name: 'removalBy', type: 'string'},
        {name: 'removalDate', type: 'date'},
        {name: 'changedBy', type: 'string'},
        {name: 'changeDate', type: 'date'},
        {name: 'approvedDeniedBy', type: 'string'},
        {name: 'approvalDeniedDate', type: 'date'},
        {name: 'removalDeniedBy', type: 'string'},
        {name: 'removalDeniedDate', type: 'date'},
        {name: 'lastModified', type: 'date'},
        {name: 'spareField01', type: 'string'},
        {name: 'spareField02', type: 'string'},
        {name: 'spareField03', type: 'string'},
        {name: 'spareIndexedField', type: 'string'}
    ],

    proxy: {
        url: 'member/{0}/memberlockssummary',
        extraParams: {
            pLockType: 'NPI',
            pRecipientId: 0
        }
    }
});
