
/*
 * Last Developer: Srujith Cheruku
 * Date: 10-26-2016
 * Previous Developers: []
 * Origin: MHP Member - View SBC
 * Description: Store for the View SBC Page
 */

Ext.define('Atlas.portals.hpmember.model.MemberPolicyWeb', {
    extend: 'Atlas.common.model.Base',

    fields: [
        { name: 'recipientID', type: 'number' },
        { name:"systemID" , type:"number" },
        { name:"sbrId" , type:"string" },
        { name:"memberId" , type:"string" },
        { name:"paymentTranId" , type:"string" },
        { name:"previousSbrId" , type:"string" },
        { name:"eligBeginDate" , type:"date" },
        { name:"eligEndDate" , type:"date" },
        { name:"covBeginDate" , type:"date" },
        { name:"covEndDate" , type:"date" },
        { name:"lastPeriodPaidDate" , type:"date" },
        { name:"benefitPlanCode" , type:"string" },
        { name:"policyNum" , type:"string" },
        { name:"otherPayAmt" , type:"number" },
        { name:"otherPayBeginDate" , type:"date" },
        { name:"otherPayEndDate" , type:"date" },
        { name:"aptcAmt" , type:"number" },
        { name:"aptcBeginDate" , type:"date" },
        { name:"aptcEndDate" , type:"date" },
        { name:"csrAmt" , type:"number" },
        { name:"csrBeginDate" , type:"date" },
        { name:"csrEndDate" , type:"date" },
        { name:"premiumAmt_1" , type:"number" },
        { name:"premiumAmt_2" , type:"number" },
        { name:"premiumAmt_3" , type:"number" },
        { name:"premiumAmt_4" , type:"number" },
        { name:"premiumAmt_5" , type:"number" },
        { name:"premiumBeginDate_1" , type:"date" },
        { name:"premiumBeginDate_2" , type:"date" },
        { name:"premiumBeginDate_3" , type:"date" },
        { name:"premiumBeginDate_4" , type:"date" },
        { name:"premiumBeginDate_5" , type:"date" },
        { name:"premiumEndDate_1" , type:"date" },
        { name:"premiumEndDate_2" , type:"date" },
        { name:"premiumEndDate_3" , type:"date" },
        { name:"premiumEndDate_4" , type:"date" },
        { name:"premiumEndDate_5" , type:"date" },
        { name:"ratingArea" , type:"string" },
        { name:"sourceExchangeId" , type:"string" },
        { name:"sourceExchangeDate" , type:"date" },
        { name:"sepReason" , type:"string" },
        { name:"sepBeginDate" , type:"date" },
        { name:"totalResAmt" , type:"number" },
        { name:"totalResBeginDate" , type:"date" },
        { name:"totalPremiumAmt" , type:"number" },
        { name:"totalPremiumBeginDate" , type:"date" },
        { name:"requestTimeStamp" , type:"string" },
        { name:"requestTimeBeginDate" , type:"date" },
        { name:"indResAmt_1" , type:"number" },
        { name:"indResAmt_2" , type:"number" },
        { name:"indResAmt_3" , type:"number" },
        { name:"indResAmt_4" , type:"number" },
        { name:"indResAmt_5" , type:"number" },
        { name:"indResAmtBeginDate_1" , type:"date" },
        { name:"indResAmtBeginDate_2" , type:"date" },
        { name:"indResAmtBeginDate_3" , type:"date" },
        { name:"indResAmtBeginDate_4" , type:"date" },
        { name:"indResAmtBeginDate_5" , type:"date" },
        { name:"totalIndResAmt" , type:"number" },
        { name:"totalIndResAmtFromDate" , type:"date" },
        { name:"totalPremiumEndDate" , type:"date" },
        { name:"totalIndResAmtEndDate" , type:"date" },
        { name:"relationCode" , type:"string" },
        { name:"totalResAmtEndDate" , type:"date" },
        { name:"ratingAreaBeginDate" , type:"date" },
        { name:"ratingAreaEndDate" , type:"date" },
        { name:"requestTimeEndDate" , type:"date" },
        { name:"sepEndDate" , type:"date" },
        { name:"indResAmtEndDate_1" , type:"date" },
        { name:"indResAmtEndDate_2" , type:"date" },
        { name:"indResAmtEndDate_3" , type:"date" },
        { name:"indResAmtEndDate_4" , type:"date" },
        { name:"indResAmtEndDate_5" , type:"date" },
        { name:"planPolicyNum" , type:"string" },
        { name:"initialPaymentFlag" , type:"boolean" },
        { name:"deliquentDays" , type:"number" },
        { name:"gracePeriodEndDate" , type:"date" },
        { name:"seqNum" , type:"number" },
        { name:"premWithHoldOption" , type:"string" },
        { name:"lepAmount" , type:"number" },
        { name:"annualIncome" , type:"number" },
        { name:"incomeGroup" , type:"number" },
        { name:"salaryGrade" , type:"number" },
        { name:"magiIndicator" , type:"string" },
        { name:"memberContribution" , type:"number" },
        { name:"mhpContribution" , type:"number" },
        { name:"maxCopayOOP" , type:"number" },
        { name:"contributionPercent" , type:"number" },
        { name:"isVoluntaryCancelTerm" , type:"boolean" },
        { name:"tobaccoUse" , type:"string" },
        { name:"maintenanceEffDate" , type:"date" },
        { name:"agentFirstName" , type:"string" },
        { name:"agentMiddleName" , type:"string" },
        { name:"agentLastName" , type:"string" },
        { name:"NPN" , type:"string" },
        { name:"benefitGroup" , type:"string" },
        { name:"planCode" , type:"string" },
        { name:"variant" , type:"string" },
        { name:"ratingareadisplay" , type:"string" },
        { name:"benefitPlanDesc" , type:"string" },
        { name:"rowNum" , type:"number" },
        { name:"dbRowID" , type:"string" }
    ],

    proxy: {
        extraParams: {

        },

        url: 'member/hp/memberpolicy'
    }
});
